In [1]:
import numpy as np
arr=np.array([[2,5,6],[5,7,2]])
arr

array([[2, 5, 6],
       [5, 7, 2]])

In [6]:
arr1=np.array([1,2,3,1,1,4])
print(arr1[arr1>3])

[4]


In [7]:
np.where(arr1>2,"a","b")

array(['b', 'b', 'a', 'b', 'b', 'a'], dtype='<U1')

In [11]:
np.unique(arr1)
np.sort(arr1)

array([1, 1, 1, 2, 3, 4])

In [19]:
arr11=arr1.reshape(2,3)
arr11.shape

(2, 3)

In [22]:
arr

array([[2, 5, 6],
       [5, 7, 2]])

In [21]:
arr11

array([[1, 2, 3],
       [1, 1, 4]])

In [25]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Addition:\n", A + B)
print("Multiplication:\n", np.matmul(A, B))
print("Transpose:\n", A.T)

Addition:
 [[ 6  8]
 [10 12]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]


In [4]:
# np.sum(arr,axis=0)
# np.matmul(arr,arr)


In [2]:
# REVISION
# =========================================
# 1. IMPORT
# =========================================
import numpy as np

# =========================================
# 2. CREATE ARRAYS
# =========================================

arr1 = np.array([1, 2, 3])              # 1D array
arr2 = np.array([[1, 2], [3, 4]])      # 2D array

np.zeros((2,3))   # all zeros
np.ones((2,3))    # all ones
np.eye(3)         # identity matrix

# =========================================
# 3. ARRAY PROPERTIES
# =========================================

print(arr2.shape)   # (rows, cols)
print(arr2.ndim)    # dimensions
print(arr2.size)    # total elements

# =========================================
# 4. INDEXING & SLICING
# =========================================

arr = np.array([10, 20, 30, 40])

print(arr[0])       # first element
print(arr[1:3])     # slicing

# 2D indexing
arr2 = np.array([[1,2],[3,4]])
print(arr2[0,1])    # row 0, col 1

# =========================================
# 5. ARRAY OPERATIONS (VECTORIZED)
# =========================================

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)   # element-wise addition
print(a * b)   # element-wise multiplication

# =========================================
# 6. BROADCASTING
# =========================================

print(a + 5)   # add scalar to all elements

# =========================================
# 7. BASIC FUNCTIONS
# =========================================

arr = np.array([1,2,3,4])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

# =========================================
# 8. RESHAPING
# =========================================

arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))   # reshape

# =========================================
# 9. RANDOM
# =========================================

np.random.rand(3)           # random floats
np.random.randint(1,10,5)   # random integers

# =========================================
# 🔴 ADVANCED NUMPY
# =========================================

# =========================================
# 10. BOOLEAN INDEXING
# =========================================

arr = np.array([10,20,30,40])
print(arr[arr > 20])   # filter values

# =========================================
# 11. FANCY INDEXING
# =========================================

print(arr[[0,2]])   # select multiple indices

# =========================================
# 12. AXIS OPERATIONS
# =========================================

arr = np.array([[1,2],[3,4]])

print(np.sum(arr))         # total
print(np.sum(arr, axis=0)) # column-wise
print(np.sum(arr, axis=1)) # row-wise

# =========================================
# 13. FLATTEN
# =========================================

arr = np.array([[1,2],[3,4]])
print(arr.flatten())   # convert to 1D

# =========================================
# 14. STACKING
# =========================================

a = np.array([1,2])
b = np.array([3,4])

print(np.vstack((a,b)))   # vertical
print(np.hstack((a,b)))   # horizontal

# =========================================
# 15. LINEAR ALGEBRA
# =========================================

a = np.array([1,2])
b = np.array([3,4])

print(np.dot(a,b))   # dot product

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.matmul(A,B))   # matrix multiplication
print(A.T)              # transpose

# =========================================
# 16. BROADCASTING (ADVANCED)
# =========================================

arr = np.array([[1,2,3],[4,5,6]])
print(arr + np.array([1,1,1]))   # row-wise addition

# =========================================
# 17. WHERE
# =========================================

arr = np.array([10,20,30,40])
print(np.where(arr > 20, "High", "Low"))

# =========================================
# 18. UNIQUE & SORT
# =========================================

arr = np.array([3,1,2,3,2])
print(np.unique(arr))
print(np.sort(arr))

# =========================================
# 19. PERFORMANCE TEST
# =========================================

import time

arr = np.arange(1000000)

start = time.time()
arr * 2
print("NumPy time:", time.time() - start)

# =========================================
# 20. MATRIX MULTIPLICATION RULE FIX (IMPORTANT)
# =========================================

arr = np.array([[2,5,6],[5,7,2]])  # shape (2x3)

print(np.sum(arr, axis=0))  # column sum

# FIX (use transpose)
print(np.matmul(arr, arr.T))  # valid (2x3)*(3x2)

# =========================================
# DONE ✅
# =========================================

(2, 2)
2
4
10
[20 30]
2
[5 7 9]
[ 4 10 18]
[6 7 8]
10
2.5
4
1
[[1 2 3]
 [4 5 6]]
[30 40]
[10 30]
10
[4 6]
[3 7]
[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]
11
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[2 3 4]
 [5 6 7]]
['Low' 'Low' 'High' 'High']
[1 2 3]
[1 2 2 3 3]
NumPy time: 0.0036644935607910156
[ 7 12  8]
[[65 57]
 [57 78]]
